export const singleserice = [
    {
        name: "SEO Articles",
        total: "130 Orders",
        path: "/services/SEO",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
        related: ["Product Description and Reviews", "Technology", "Digital Marketing"],
    },
    {
        name: "Product Description and Reviews",
        path: "/services/Product-Description-and-Reviews",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
        total: "305 Orders",
        related: ["SEO", "Technology", "Digital Marketing"],
    },

    {
        name: "Technology Article",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
        path: "/services/Technology",
        related: ["Product Description and Reviews", "Technology", "Digital Marketing"],
        total: "65 Orders",
    },
    {
        name: "Education Articles",
        related: ["Recipes", "Technology", "Ghostwriting"],
        total: "64 Orders",
        path: "/services/Education",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Digital Marketing Articles",
        related: ["Product Description and Reviews", "Technology", "SaaS (Software-as-a-Service)"],
        total: "86 Orders",
        path: "/services/Digital-Marketing",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",

    },
    {
        name: "Recipes Articles",
        related: ["Food and beverages", "Outdoor and back life activities", "Health and wellness"],
        total: "93 Orders",
        path: "/services/Recipes",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Food and Beverage Article",
        related: ["Recipes", "Outdoor and back life activities", "Health and wellness"],
        total: "34 Orders",
        path: "/services/Food-and-beverages",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Outdoor and back life activities",
        related: ["Recipes", "Exercise and fitness", "Health and wellness"],
        total: "123 Orders",
        path: "/services/Outdoor-and-back-life-activities",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Health and wellness Article",
        related: ["Sports", "Exercise and fitness", "Outdoor and back life activities"],
        total: "103 Orders",
        path: "/services/Health-and-wellness",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Exercise and fitness Article",
        related: ["Sports", "Outdoor and back life activities", "Health and wellness"],
        total: "155 Orders",
        path: "/services/Exercise-and-fitness",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Sports Article",
        related: ["Exercise and fitness", "Outdoor and back life activities", "Health and wellness"],
        total: "94 Orders",
        path: "/services/Sportes",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: " Fashion and beauty Article",
        related: ["Relationships", "Outdoor and back life activities", "Health and wellness"],
        total: "155 Orders",
        path: "/services/Fashion-and-beauty",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",

    },
    {
        name: "Relationships Article",
        related: ["Alternative health(CBD)", "Outdoor and back life activities", "Travel"],
        total: "74 Orders",
        path: "/services/Relationships",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "SaaS (Software-as-a-Service) Article",
        related: ["Technology", "Blog post", "White papers"],
        total: "32 Orders",
        path: "/services/Software-as-a-Service",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Alternative health(CBD) Article",
        related: ["Sports", "Exercise and fitness", "Outdoor and back life activities"],
        total: "155 Orders",
        path: "/services/Alternative-health(CBD)",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Real Estate Articles",
        related: ["Travel", "Home decor", "Parenting"],
        total: "87 Orders",
        path: "/services/Real-Estate",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Travel Articles",
        total: "92 Orders",
        related: ["Real Estate", "Home decor", "Parenting"],
        path: "/services/Travel",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Ghostwriting",
        total: "150 Orders",
        related: ["Blog post", "Business plans", "White papers"],
        path: "/services/Ghostwriting",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Blog post Articles",
        related: ["Video and movie scripts", "Business plans", "White papers"],
        total: "502 Orders",
        path: "/services/Blog-post",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Business plans",
        related: ["Blog post", "Pregnancy", "White papers"],
        total: "194 Orders",
        path: "/services/Business-plans",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "White papers",
        total: "64 Orders",
        related: ["Blog post", "Pets", "Parenting"],
        path: "/services/White-papers",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Video and movie scripts",
        total: "35 Orders",
        related: ["Blog post", "Pets", "Parenting"],
        path: "/services/Video-and-movie-scripts",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Hemp Cannabis Articles",
        total: "40 Orders",
        related: ["Alternative health(CBD)", "Pets", "Parenting"],
        path: "/services/Hemp-Cannabis",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Parenting Articles",
        total: "135 Orders",
        related: ["Home decor", "Pets", "Pregnancy"],
        path: "/services/Parenting",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Home decor Articles",
        total: "77 Orders",
        related: ["Real Estate", "Pets", "Pregnancy"],
        path: "/services/Home-decor",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Pregnancy Articles",
        total: "145 Orders",
        related: ["Alternative health(CBD)", "Parenting", "Relationships"],
        path: "/services/Pregnancy"
    },
    {
        name: "Pets Articles",
        total: "93 Orders",
        related: ["Home decor", "Travel", "Relationships"],
        path: "/services/Pets",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "General Contents",
        total: "183 Orders",
        related: ["SEO", "Travel", "Relationships"],
        path: "/services/General-contents",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Term Paper Wrinting",
        total: "121 Orders",
        related: ["Research Paper Writing", "Article Critique Writing", "Argumentative Essay Writing"],
        path: "/services/Term-Paper-Wrinting",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Research Paper Writing ",
        related: ["Term Paper Wrinting", "Article Critique Writing", "Argumentative Essay Writing"],
        total: "138 Orders",
        path: "/services/Research-Paper-Writing",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },


    {
        name: "Argumentative Essay Writing",
        related: ["Analsis Paper Writing", "Article Critique Writing", "Research Paper Writing"],
        total: "302 Orders",
        path: "/services/Argumentative-Essay-Writing",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Analsis Paper Writing",
        related: ["Term Paper Wrinting", "Article Critique Writing", "Research Paper Writing"],
        total: "146 Orders",
        path: "/services/Analsis-Paper-Writing",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },

    {
        name: "Addmission Essay Writing",
        related: ["Term Paper Wrinting", "Article Critique Writing", "Research Paper Writing"],
        total: "124 Orders",
        path: "/services/Addmission-Essay-Writing",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Article Critique Writing",
        related: ["Term Paper Wrinting", "Annotated Bibliography Writing", "Argumentative Essay Writing"],
        total: "156 Orders",
        path: "/services/Article-Critique-Writing",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Annotated Bibliography Writing",
        related: ["Term Paper Wrinting", "Article Critique Writing", "Argumentative Essay Writing"],
        total: "152 Orders",
        path: "/services/Annotated-Bibliography-Writing",

        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },

    {
        name: "Book Review Writing",
        related: ["Literature Review Writing", "Marketing Plan Essay Writing", "Research Paper Writing"],
        total: "155 Orders",
        path: "/services/Book-Review-Writing",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    }
    ,
    {
        name: "Case Study Writing",
        related: ["Literature Review Writing", "Marketing Plan Essay Writing", "Research Paper Writing"],
        total: "153 Orders",
        path: "/services/Case-Study-Writing",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Literature Review Writing",
        related: ["Book Review Writing", "Marketing Plan Essay Writing", "Research Paper Writing"],
        total: "285 Orders",
        path: "/services/Literature-Review-Writing",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },

    {
        name: "Marketing Plan Essay Writing",
        related: ["Finance and accounting Assignment", "Case Brief Writing", "Research Paper Writing"],
        total: "127 Orders",
        path: "/services/Marketing-Plan-Essay-Writing",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "IB internal Assessment",
        related: ["Finance and accounting Assignment", "Programming Assignment", "Research Paper Writing"],
        total: "98 Orders",
        path: "/services/IB-internal-Assessment",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Marketing Plan Essay Writing",
        related: ["Finance and accounting Assignment", "Case Brief Writing", "Research Paper Writing"],
        total: "201 Orders",
        path: "/services/Finance-and-accounting-Assignment",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },

    {
        name: "Programming Assignment",
        related: ["Finance and accounting Assignment", "Case Brief Writing", "Write my Essay for me"],
        total: "100 Orders",
        path: "/services/Programming-Assignment",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    }
    ,

    {
        name: "Case Brief Writing",
        related: ["Research Paper Writing", "IB internal Assessment", "Term Paper Wrinting"],
        total: "55 Orders",
        path: "/services/Case-Brief-Writing",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },

    {
        name: "Capson Project Writing",
        related: ["Research Paper Writing", "Extended Essay Writing", "Term Paper Wrinting"],
        total: "18 Orders",
        path: "/services/Write-my-Capson-Project",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Extended Essay Writing",
        related: ["Research Paper Writing", "Dissertation Writing", "Programming Assignment"],
        total: "130 Orders",
        path: "/services/Extended-Essay-Writing",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    },
    {
        name: "Dissertation Writing",
        related: ["Case Brief Writing", "Extended Essay Writing", "Term Paper Wrinting"],
        total: "134 Orders",
        path: "/services/Dissertation-Writing",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae deserunt minus sunt repellat aliquam. Provident porro consequatur excepturi. Nobis cum modi ipsa architecto ex molestiae velit nemo obcaecati enim debitis.",
    }
];
